# Change these first
owner: ComradeTurtle # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: meteora-weather.gr
    url: $MWURL
    __dangerous__body_down: "fail"
    __dangerous__body_degraded: "degraded"
    maxResponseTime: 3000
    icon: https://meteora-weather.gr/favicon.ico
  - name: apousies.gr
    url: $APURL
    __dangerous__body_down: "fail"
    __dangerous__body_degraded: "degraded"
    icon: https://apousies.gr/favicon.ico
  - name: Home Assistant
    url: $HAURL
    headers:
      - "Authorization: $HATOKEN"
      - "Content-Type: application/json"
    __dangerous__body_down_if_text_missing: "API running"
    icon: https://www.home-assistant.io/images/favicon.ico
  - name: RIPE Atlas Probe
    url: $ATLURL
    icon: https://www.ripe.net/favicon.ico
    __dangerous__body_down_if_text_missing: "Connected"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.comradeturtle.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ComradeTurtle - Status
  introTitle: "Realtime status updates on all of my services."
  introMessage: "Here you will find the status of all my selfhosted services - including the not public facing ones. Updates every 5 minutes."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Contact
      href: mailto:giorgosd1300@shadowct.eu

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
